---

    name: Cleanup old images published to ghcr
    
    on:
      schedule:
        - cron:  '0 21 * * *'
      workflow_dispatch:
    env:
      IMAGE_NAME: "oidc-php-client"
      SUCCESS_ICON: ":white_check_mark:"
      ERROR_ICON: ":exclamation:"
      INFO_ICON: ":information_source:"
    
    jobs:
      cleanup_old_images:
        runs-on: ubuntu-latest
    
        steps:
          - name: cleanup old images
            id: cleanup
            uses: snok/container-retention-policy@4f22ef80902ad409ed55a99dc5133cc1250a0d03
            with:
              image-names: ${{ env.IMAGE_NAME }}
              cut-off: "5m"
              timestamp-to-use: updated_at
              account: ucidentity
              keep-at-least: 3
              image-tags: "!latest"
              token: ${{ secrets.GITHUB_TOKEN }}
              
          - name: Send Slack message if images have been deleted
            id: slack
            uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e
            with:
              payload: |
                {
                  "message": "${{ env.INFO_ICON }} Old images have been deleted\n\n${{ steps.cleanup.outputs.deleted }}"
                }
            env:
              SLACK_WEBHOOK_URL: ${{ secrets.CALNET_SLACK_GHA_WEBHOOK_URL }}
            if: steps.cleanup.outputs.deleted != ''
    
