name: Create and publish container image

on:
  push:
    tags:
      - 'v**'
  workflow_dispatch:
  schedule:
    - cron: '20 17 * * 2'  # Every Tuesday of the month at 9:20 am

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: oidc-php-client
  BASE_IMAGE_DOCKERFILE: ./Dockerfile

jobs:

  check:
    runs-on: ubuntu-latest

    outputs:
      differs: ${{ steps.check.outputs.differs }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set base image
        run: |
          echo "BASE_IMAGE=$(grep 'FROM' ${{ env.BASE_IMAGE_DOCKERFILE}} | awk '{print $2}')" >> "$GITHUB_ENV"

      - name: Debug
        run: |
          echo ${{ env.BASE_IMAGE }}

      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Check if update available
        id: check
        uses: ClementTsang/docker-check-base-image-diff@d8cf79d3bcda38fab44bc8c9afa60c4b3dee23de
        with:
          base-image: docker://${{ env.BASE_IMAGE }}
          derived-image: docker://${{ env.REGISTRY }}/ucidentity/${{ env.IMAGE_NAME }}

  publish:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # When invoked by schedule, only build if the base image is out of date
    if: ${{ needs.check.outputs.differs == 'true' ||  github.event_name != 'schedule' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for container
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REGISTRY }}/ucidentity/${{ env.IMAGE_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags:
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}

      - name: Build and push container image
        uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/ucidentity/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
